image: docker:latest

variables:

  DOCKER_API_VERSION: "1.39"

build:
  stage: build
  script:
    - docker build --build-arg HTTPS_PROXY=$HTTPS_PROXY --build-arg https_proxy=$HTTPS_PROXY --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg http_proxy=$HTTP_PROXY --build-arg NO_PROXY=$NO_PROXY --build-arg no_proxy=$NO_PROXY -f docker/base/Dockerfile -t vdms:test .

run tests:
  stage: test
  script:
    - docker build --build-arg HTTPS_PROXY=$HTTPS_PROXY --build-arg https_proxy=$HTTPS_PROXY --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg http_proxy=$HTTP_PROXY --build-arg NO_PROXY=$NO_PROXY --build-arg no_proxy=$NO_PROXY -f docker/base/Dockerfile -t vdms:test .
    - docker run --env HTTPS_PROXY=$HTTPS_PROXY --env https_proxy=$HTTPS_PROXY --env HTTP_PROXY=$HTTP_PROXY --env http_proxy=$HTTP_PROXY --env NO_PROXY=$NO_PROXY --env no_proxy=$NO_PROXY --dns 10.248.2.1 -v ./:/vdms vdms:test bash -c "pip install coverage vdms diff_cover && cd /vdms/tests/python && ./run_python_tests.sh"
  artifacts:
    reports:
      cobertura: coverage.xml

