image: "ubuntu:20.04"

variables:
  HTTP_PROXY: http://proxy-chain.intel.com:911
  HTTPS_PROXY: http://proxy-chain.intel.com:912
  
before_script:
  - mkdir -p $HOME/.docker/
  - 'echo "{ \"proxies\": { \"default\": { \"httpProxy\": \"$HTTP_PROXY\", \"httpsProxy\": \"$HTTPS_PROXY\", \"noProxy\": \"$NO_PROXY\" } } }" > $HOME/.docker/config.json'
  - cat $HOME/.docker/config.json
  - env
  - apt-get update

build:
  stage: build
  script:
    - ls -l

test:
  stage: test
  script:
    - ls -l
