# PROJECT INFORMATION
site_name: VDMS Documentation
site_url: https://intellabs.github.io/vdms/
repo_url: http://github.com/IntelLabs/vdms
copyright: Copyright &copy; 2025 Intel Corporation

# DOCUMENTATION LAYOUT
nav:
  - Home: "index.md"
  - Getting Started:
      - Install: "Install.md"
      - Docker: "Docker.md"
      - VDMS Mutual TLS Support: "guides/VDMS-mTLS-Support.md"
  - API (v2.0.0++):
      - Description: "API-Description.md"
      - ConfigFile: "ConfigFile.md"
      - Keywords: "Keywords.md"
      - Returned Status: "Returned-Status.md"
      - Schema Definition: "Schema.md"
      - Commands:
          - Basic Building Blocks: "commands/basic_building_blocks_index.md"
          - Insert: "commands/insert_index.md"
          - Query: "commands/query_index.md"
          - Update: "commands/update_index.md"
  - Tutorials & Guides:
      - Tutorials:
        - Simple Tutorial: "guides/Simple-Tutorial.md"
        - Image Tutorial: "guides/Image-Tutorial.md"
        - Descriptor Tutorial: "guides/Descriptor-Tutorial.md"
      - How-to Guides:
        - Backends & Query Handlers:
          - Neo4j based Scale Out: "guides/Neo4J-Based-Scale-Out-VDMS.md"
          - Query Handler Development: "guides/Query-Handler-Development.md"
        - Connectors & Orchestrations:
          - Kafka Connectors for VDMS: "guides/Run-Kafka-VDMS-Example.md"
          - Kubernetes Orchestration in VDMS: "guides/Kubernetes-Orchestration.md"
        - CSV Plugin for C++ Client: "guides/CSV-Plugin-for-CPP-Client.md"
        - Deletion, Backup, & Restore:
          - Auto-Deletion of Expired Data: "guides/Auto-Deletion-of-Expired-Data.md"
          - Backup and Restoring Options: "guides/VDMS-Backup-and-Restoring-Options.md"
          - Deletion Capabilities: "guides/Deletion-Capabilities.md"
        - Descriptors:
          - Descriptors Memory Usage: "guides/Descriptor-Memory-Usage.md"
          - FLINNG Library and Performance: "guides/FLINNG-Library-and-Performance.md"
        - Remote & User Defined Operations:
          - Remote Operations: "guides/Remote-Operations.md"
          - User Defined Operations: "guides/User-Defined-Operations.md"
          - Dynamically Add Metadata: "guides/Dynamic-Metadata.md"
        - Remote Storage: "guides/Remote-Storage-in-VDMS.md"
        - Timing Capability: "guides/Timing-Capability.md"
  - Interactive Guide:
      - DeepWiki: "https://deepwiki.com/IntelLabs/vdms"
  - Contribute:
      - Developer Guide: "guides/Developer-Guide.md"
      - VDMS Test Suite: "guides/VDMS-Test-Suite.md"
not_in_nav: |
  blocks/*
  commands/Add*.md
  commands/Classify*.md
  commands/Find*.md
  commands/Neo*.md
  commands/Update*.md
  guides/Archive-a-VDMS-Database.md
  guides/Auto-Deletion-of-Expired-Data.md
  guides/CSV-Plugin-for-C++-Client.md
  guides/Custom-VCL-Image-Manipulation-Functions.md
  guides/Deletion-Capabilities.md
  guides/Descriptor-Memory-Usage.md
  guides/Descriptor-Tutorial.md
  guides/Dynamic-Metadata.md
  guides/FLINNG-Library-and-Performance.md
  guides/Image-Tutorial.md
  guides/Kubernetes-Orchestration.md
  guides/Neo4J-Based-Scale-Out-VDMS.md
  guides/Query-Handler-Development.md
  guides/Read-Only-Docker-Container.md
  guides/Remote-Operations.md
  guides/Remote-Storage-in-VDMS.md
  guides/Run-Kafka-VDMS-Example.md
  guides/Simple-Tutorial.md
  guides/Timing-Capability.md
  guides/User-Defined-Operations.md
  guides/VDMS-Backup-and-Restoring-Options.md
  guides/VDMS-Test-Script.md

# BUILD DIRECTORIES
theme:
  name: readthedocs
  # name: material
  palette:
    - primary: light blue

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  # logo: images/IL_logo.png
  icon:
    logo: material/database
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

# FORMATTING OPTIONS
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.snippets:
      url_download: true
plugins:
  - search
