# PROJECT INFORMATION
site_name: VDMS Documentation
site_url: https://intellabs.github.io/vdms/
repo_url: http://github.com/IntelLabs/vdms
copyright: Copyright &copy; 2025 Intel Corporation
edit_uri: http://github.com/IntelLabs/vdms/blob/develop/docs/

# DOCUMENTATION LAYOUT
nav:
  - Home: "index.md"
  - Getting Started:
      - Install: "Install.md"
      - Docker: "Docker.md"
      - VDMS Mutual TLS Support: "guides/VDMS-mTLS-Support.md"
  - API (v2.0.0++):
      - Description: "API-Description.md"
      - ConfigFile: "ConfigFile.md"
      - Keywords: "Keywords.md"
      - Returned Status: "Returned-Status.md"
      - Schema Definition: "Schema.md"
      - Commands:
        - Basic Building Blocks: # "commands/basic_building_blocks_index.md"
            - Constraints: "blocks/Block-constraints.md"
            - Link: "blocks/Block-link.md"
            - Operations: "blocks/Block-operations.md"
            - Properties: "blocks/Block-properties.md"
            - Rectangle: "blocks/Block-rectangle.md"
            - Results: "blocks/Block-results.md"
        - Insert:   #"commands/insert_index.md"
            - AddBlob: "commands/AddBlob.md"
            - AddBoundingBox: "commands/AddBoundingBox.md"
            - AddConnection: "commands/AddConnection.md"
            - AddDescriptor: "commands/AddDescriptor.md"
            - AddDescriptorSet: "commands/AddDescriptorSet.md"
            - AddEntity: "commands/AddEntity.md"
            - AddImage: "commands/AddImage.md"
            - AddVideo: "commands/AddVideo.md"
            - NeoAdd: "commands/NeoAdd.md"
            - NeoAddDescriptor: "commands/NeoAddDescriptor.md"
            - NeoAddDescriptorSet: "commands/NeoAddDescriptorSet.md"
        - Query: #"commands/query_index.md"
            - ClassifyDescriptor: "commands/ClassifyDescriptor.md"
            - FindBlob: "commands/FindBlob.md"
            - FindBoundingBox: "commands/FindBoundingBox.md"
            - FindConnection: "commands/FindConnection.md"
            - FindDescriptor: "commands/FindDescriptor.md"
            - FindDescriptorSet: "commands/FindDescriptorSet.md"
            - FindEntity: "commands/FindEntity.md"
            - FindFrames: "commands/FindFrames.md"
            - FindImage: "commands/FindImage.md"
            - FindVideo: "commands/FindVideo.md"
            - NeoFind: "commands/NeoFind.md"
            - NeoFindDescriptor: "commands/NeoFindDescriptor.md"
            - NeoFindDescriptorSet: "commands/NeoFindDescriptorSet.md"
        - Update: # "commands/update_index.md"
            - UpdateBlob: "commands/UpdateBlob.md"
            - UpdateBoundingBox: "commands/UpdateBoundingBox.md"
            - UpdateConnection: "commands/UpdateConnection.md"
            - UpdateEntity: "commands/UpdateEntity.md"
            - UpdateImage: "commands/UpdateImage.md"
            - UpdateVideo: "commands/UpdateVideo.md"
  - Tutorials & Guides:
      - Tutorials:
        - Simple Tutorial: "tutorials/Simple-Tutorial.md"
        - Image Tutorial: "tutorials/Image-Tutorial.md"
        - Descriptor Tutorial: "tutorials/Descriptor-Tutorial.md"
      - How-to Guides:
        - Backends & Query Handlers:
          - Neo4j based Scale Out: "guides/backends-and-handlers/Neo4J-Based-Scale-Out-VDMS.md"
          - Query Handler Development: "guides/backends-and-handlers/Query-Handler-Development.md"
        - Connectors & Orchestrations:
          - Kafka Connectors for VDMS: "guides/connectors-and-orchestrations/Run-Kafka-VDMS-Example.md"
          - Kubernetes Orchestration in VDMS: "guides/connectors-and-orchestrations/Kubernetes-Orchestration.md"
        - CSV Plugin for C++ Client: "guides/CSV-Plugin-for-CPP-Client.md"
        - Deletion, Backup, & Restore:
          - Auto-Deletion of Expired Data: "guides/deletion-backup-and-restore/Auto-Deletion-of-Expired-Data.md"
          - Backup and Restoring Options: "guides/deletion-backup-and-restore/VDMS-Backup-and-Restoring-Options.md"
          - Deletion Capabilities: "guides/deletion-backup-and-restore/Deletion-Capabilities.md"
        - Descriptors:
          - Descriptors Memory Usage: "guides/descriptors/Descriptor-Memory-Usage.md"
          - FLINNG Library and Performance: "guides/descriptors/FLINNG-Library-and-Performance.md"
        - Remote & User Defined Operations:
          - Remote Operations: "guides/remote-and-udf-operations/Remote-Operations.md"
          - User Defined Operations: "guides/remote-and-udf-operations/User-Defined-Operations.md"
          - Dynamically Add Metadata: "guides/remote-and-udf-operations/Dynamic-Metadata.md"
        - Remote Storage: "guides/Remote-Storage-in-VDMS.md"
        - Timing Capability: "guides/Timing-Capability.md"
  - Interactive Guide:
      - DeepWiki: "https://deepwiki.com/IntelLabs/vdms"
  - Contribute:
      - Developer Guide: "contribute/Developer-Guide.md"
      - Test Suite:
        - VDMS Test Suite Overview: "contribute/VDMS-Test-Suite.md"
        - VDMS Test Script: "contribute/VDMS-Test-Script.md"
not_in_nav: |
  blocks/*
  # commands/Add*.md
  commands/Classify*.md
  # commands/Find*.md
  # commands/Neo*.md
  commands/NeoClassifyDescriptor.md
  # commands/Update*.md
  guides/*

# BUILD DIRECTORIES
theme:
  name: readthedocs
  # name: material
  palette:
    - primary: light blue

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  # logo: images/IL_logo.png
  icon:
    logo: material/database
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

# FORMATTING OPTIONS
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
plugins:
  - search
