#!/bin/bash -e

rm -rf jsongraph || true
rm -rf qhgraph || true
rm -rf simpleAdd_db || true
rm -rf simpleAddx10_db || true
rm -rf simpleUpdate_db || true
rm -rf entitycheck_db || true
rm -rf datatypecheck_db || true
rm -rf db_backup || true
rm -rf test_db_1 || true
rm -rf tests_log.log || true
rm -rf tests_screen.log || true
rm -rf tests_remote_screen.log || true
rm -rf tests_remote_log.log || true
rm -rf tests_udf_screen.log || true
rm -rf tests_udf_log.log || true
rm -rf tdb/ || true
rm -rf db || true
rm -rf dbs || true
rm -rf test_db_client || true
rm -rf temp || true
rm -rf videos_tests || true
rm -rf vdms || true
rm -rf test_images/tdb_to_jpg.jpg || true
rm -rf test_images/tdb_to_png.png || true
rm -rf test_images/test_image.jpg || true
rm -rf remote_function_test/tmpfile* || true
rm -rf remote_function_test/jsonfile* || true
rm -rf backups || true
rm -rf ../minio_files || true
rm -rf ../test_db || true
rm -rf ../test_db_aws || true
rm -rf test_db_tls || true
rm -rf python/test_db_tls || true
rm -rf screen-tls.log || true
rm -rf log-tls.log || true
rm -rf /tmp/trusted_ca_cert.pem || true
rm -rf /tmp/trusted_server_cert.pem || true
rm -rf /tmp/trusted_server_key.pem || true
rm -rf /tmp/trusted_client_cert.pem || true
rm -rf /tmp/trusted_client_key.pem || true
rm -rf /tmp/untrusted_client_cert.pem || true
rm -rf /tmp/untrusted_client_key.pem || true
rm -rf /tmp/rpathimage.jpg || true