# We need to add this dependecy.
Import('env')
import os

testenv = env.Clone()

testenv.Replace(
    CPPPATH= ['../src', '../include', '../utils/include', '../src/vcl/',
              '/usr/include/jsoncpp/',
              os.path.join(env['INTEL_PATH'], 'pmgd/include'),
              os.path.join(env['INTEL_PATH'], 'pmgd/util'),
             ])

testenv.Append(
        LIBS = ['gtest',
                'tiledb',
                'opencv_core',
                'opencv_imgproc',
                'opencv_imgcodecs',
                'opencv_videoio',
                'opencv_highgui',
                'gomp',
                'faiss',
                'gtest', 'pthread',
              ],

        LIBPATH = ['../utils/']
        )

testenv.MergeFlags(GetOption('cflags'))

test_sources = ['main.cc',
                'server/json_queries.cc',
                'unit_tests/pmgd_queries.cc',
                'unit_tests/helpers.cc',
                'unit_tests/TDBImage_test.cc',
                'unit_tests/Image_test.cc',
                'unit_tests/Video_test.cc',
                'unit_tests/DescriptorSetAdd_test.cc',
                'unit_tests/DescriptorSetClassify_test.cc',
                'unit_tests/DescriptorSetTrain_test.cc',
                'unit_tests/DescriptorSetReadFS_test.cc',
                'unit_tests/DescriptorSetStore_test.cc',
              ]

objects_list = [ '../src/QueryHandler.o',
                  '../src/SearchExpression.o',
                  '../src/VDMSConfig.o',
                  '../src/RSCommand.o',
                  '../src/ImageCommand.o',
                  '../src/VideoCommand.o',
                  '../src/ExceptionsCommand.o',
                  '../src/PMGDIterators.o',
                  '../src/PMGDQueryHandler.o',
                  '../src/PMGDQuery.o',
                  '../src/QueryMessage.o',
                  '../src/DescriptorsManager.o',
                  '../src/DescriptorsCommand.o',
                  "../src/BoundingBoxCommand.o",

                  '../src/vcl/utils.o',
                  '../src/vcl/Exception.o',
                  '../src/vcl/TDBObject.o',
                  '../src/vcl/Image.o',
                  '../src/vcl/TDBImage.o',
                  '../src/vcl/Video.o',
                  '../src/vcl/DescriptorSet.o',
                  '../src/vcl/DescriptorSetData.o',
                  '../src/vcl/FaissDescriptorSet.o',
                  '../src/vcl/TDBDescriptorSet.o',
                  '../src/vcl/TDBDenseDescriptorSet.o',
                  '../src/vcl/TDBSparseDescriptorSet.o',
                  test_sources
                ]

if GetOption('cflags') and '-DVIDEO_KEYFRAMES' in GetOption('cflags') :
  objects_list.append('../src/vcl/KeyFrameParser.o')

query_tests = testenv.Program( 'unit_test', objects_list)
