# We need to add this dependecy.
Import('env')
import os

testenv = env.Clone()

testenv.Replace(
    CPPPATH= ['../src', '../utils/include',
              '/usr/include/jsoncpp/',
              os.path.join(env['INTEL_PATH'], 'pmgd/include'),
              os.path.join(env['INTEL_PATH'], 'pmgd/util'),
              os.path.join(env['INTEL_PATH'], 'vcl/include'),
              os.path.join(env['INTEL_PATH'], 'vcl/src'),
             ])

testenv.Append(
      LIBS = ['gtest'],
      LIBPATH = ['../utils/']
      )

testenv.MergeFlags(GetOption('cflags'))

test_sources = ['main.cc', 'pmgd_queries.cc', 'json_queries.cc']

query_tests = testenv.Program(
                'query_tests',
                [ '../src/QueryHandler.o',
                  '../src/SearchExpression.o',
                  '../src/VDMSConfig.o',
                  '../src/RSCommand.o',
                  '../src/ImageCommand.o',
                  '../src/ExceptionsCommand.o',
                  '../src/PMGDIterators.o',
                  '../src/PMGDQueryHandler.o',
                  '../src/PMGDQuery.o',
                  '../src/QueryMessage.o',
                  '../src/DescriptorsManager.o',
                  '../src/DescriptorsCommand.o',
                  test_sources
                ],
               )
