# We need to add this dependecy.
Import('env')

testenv = env.Clone()
testenv.Append(
      CPPPATH= ['../src', '../utils/include'],
      LIBS = ['gtest'],
      LIBPATH = ['../utils/']
      )

testenv.MergeFlags(GetOption('cflags'))

test_sources = ['main.cc', 'pmgd_queries.cc', 'json_queries.cc']

query_tests = testenv.Program(
                'query_tests',
                [ '../src/QueryHandler.o',
                  '../src/SearchExpression.o',
                  '../src/VDMSConfig.o',
                  '../src/RSCommand.o',
                  '../src/ImageCommand.o',
                  '../src/ExceptionsCommand.o',
                  '../src/PMGDQueryHandler.o',
                  '../src/PMGDQuery.o',
                  '../src/QueryMessage.o',
                  test_sources
                ],
               )
