#! /usr/bin/python
from struct import *
import sys
import os
import socket
import urllib
import struct
# sys.path.insert(0, '../../protobuf/')
sys.path.insert(0, '/opt/intel/athena/utils/include/protobuf/')
import queryMessage_pb2 # protobuf struct autogenerated
# import select
import time

quer = queryMessage_pb2.queryMessage()
# quer has .json_query and .blob
quer.json_query = "{HERE GOES YOUR JSON QUERY}"

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("localhost",55555))

# Serialize with protobuf and send
data = quer.SerializeToString();
val = pack('<I', len(data)) # send size first
s.send( val )
s.send(data)

time.sleep(2)


# Recieve response
val = s.recv(4)
val = struct.unpack('>I', val)[0]
response = s.recv(val)

querRes = queryMessage_pb2.queryMessage()
querRes.ParseFromString(response)

print querRes.json_query
