import os

# Set INTEL_PATH. First check arguments, then enviroment, then default
if ARGUMENTS.get('INTEL_PATH', '') != '':
  intel_path = ARGUMENTS.get("INTEL_PATH", '')
elif os.environ.get('INTEL_PATH', '') != '':
  intel_path = os.environ.get('INTEL_PATH', '')
else:
  intel_path = os.getcwd()

# Enviroment use by all the builds
env = Environment(CXXFLAGS="-std=c++11 -O3")
env.Append(INTEL_PATH= intel_path)

env.Append(CPPPATH= ['include', 'src',
		     os.path.join(env['INTEL_PATH'], 'pmgd/include'),
                     os.path.join(env['INTEL_PATH'], 'pmgd/util')
		    ])

source_files = ['src/misc_loaders.cc',
				'src/yfcc_csv_reader.cc',
				'src/yfcc.cc',
				]


env.Program('yfcc', source_files,
			LIBS = ['pmgd', 'pmgd-util', 'jsoncpp'],
			LIBPATH = [os.path.join(env['INTEL_PATH'], 'pmgd/lib/')]
			)
