apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  type: NodePort
  selector:
    app: vdms
  ports:
    - protocol: TCP
      port: 55555
      targetPort: 55555
      nodePort: 30001 # Specify the node port here, you can choose any available port