cmake_minimum_required (VERSION 3.10)
project(vdms-utils)

option(USE_K8S "Enable kubernetes client libraries" OFF)
message("USE_K8S:" ${USE_K8S})
if(USE_K8S)
    message(STATUS "Including kubernetes client libraries and kubernetes helper class")
    include_directories(include/comm include/chrono include/stats include/timers include/kubernetes /usr/include/libwebsockets)
    add_library(vdms-utils SHARED src/timers/TimerMap.cc src/comm/ConnClient.cc src/comm/Connection.cc src/comm/Exception.cc src/comm/ConnServer.cc src/stats/SystemStats.cc src/kubernetes/KubeHelper.cc)
    target_link_libraries(vdms-utils -L/usr/local/lib/ -lkubernetes)
else()
    include_directories(include/comm include/chrono include/stats include/timers)
    add_library(vdms-utils SHARED src/timers/TimerMap.cc src/comm/ConnClient.cc src/comm/Connection.cc src/comm/Exception.cc src/comm/ConnServer.cc src/stats/SystemStats.cc)
endif()