# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: entity.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'entity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ntity.proto\x12\x06\x65ntity\")\n\x06\x45ntity\x12\x0e\n\x06\x65ntity\x18\x01 \x01(\x0c\x12\x0f\n\x07options\x18\x02 \x01(\x0c\x32\x35\n\x08Operator\x12)\n\x07Operate\x12\x0e.entity.Entity\x1a\x0e.entity.Entityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTITY']._serialized_start=24
  _globals['_ENTITY']._serialized_end=65
  _globals['_OPERATOR']._serialized_start=67
  _globals['_OPERATOR']._serialized_end=120
# @@protoc_insertion_point(module_scope)
