name: Pre-commit

on:
  workflow_call:
    inputs:
      source-ref:
        required: true
        type: string
        description: "Github reference for source code"


permissions: read-all

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     branches: [develop]

# Declare default permissions as write only.
# permissions: read-all

# If another push to the same PR or branch happens while this workflow is still running,
# cancel the earlier run in favor of the next run.
#
# There's no point in testing an outdated version of the code. GitHub only allows
# a limited number of job runners to be active at the same time, so it's better to cancel
# pointless jobs early so that more useful jobs can run sooner.
# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.1.7
      with:
        submodules: false
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()
    - if: failure()
      run: |
        echo 'Pre-commit failed. Please fix issues.'
        exit 1

      # pre-success:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   steps:
  #     - run: echo 'Pre-commit completed successfully.'
  # pre-failure:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'failure' }}
  #   steps:
  #     - run: echo 'Pre-commit failed. Please fix issues.'
  # pre-exit:
  #   needs: pre-failure
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: exit 1