# Uses docker/check-in/Dockerfile without coverage or coverity
# Same as docker/base/Dockerfile but builds VDMS with local changes instead of external repo
name: SDL Requirements using Docker Image

# Controls when the action will run. Triggers the workflow on push or pull request (for testing)
# events but only for the master and develop branch
on:
  push:
    branches:
      - develop
# on:
#   pull_request:
#     types: [ opened, edited, synchronize, reopened ]
#     branches:
#       - develop
#       - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Environment variables
env:
  ARTIFACT_DIR: SDL_artifacts
  DOCKER_ARTIFACT_DIR: Docker_artifacts
  CHECKIN_DOCKERFILE: docker/check-in/Dockerfile
  # CHECKOUT_REF: ${{ github.event.pull_request.head.sha }}
  FACELESS_USERNAME: ${{ secrets.FACELESS_NAME}}
  FACELESS_AUTHKEY: ${{ secrets.FACELESS_AUTHKEY}}
  COVERITYSTREAM: ${{ secrets.COVERITYSTREAM}}
  COVERITYSERVER: ${{ secrets.COVERITYSERVER }}

jobs:
  delete:
      name: Remove old artifacts
      runs-on:
        group: intellabs-vdms-runners
        labels: vdms-check-in
      steps:
        - uses: actions/github-script@v6
          id: artifact
          with:
            # Delete all artifacts
            script: |
              const res = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
              })

              res.data.artifacts
                .forEach(({ id }) => {
                  github.rest.actions.deleteArtifact({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    artifact_id: id,
                  })
                })

  # RUN HADOLINT & BANDIT; NO DOCKER BUILD NEEDED
  Hadolint:
    # Check format of Dockerfile we will release (docker/base/Dockerfile)
    name: Haskell Dockerfile Linter
    needs: delete
    runs-on:
      group: intellabs-vdms-runners
      labels: vdms-check-in
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ env.CHECKOUT_REF }}
      - run: mkdir -p ${{ env.ARTIFACT_DIR }}
      - name: Run Hadolint Docker Container
        id: get_hadolint
        run: |
          set -x
          docker run --rm --env HADOLINT_FORMAT=gnu -i hadolint/hadolint:latest < docker/base/Dockerfile 2>&1 | tee ${{ env.ARTIFACT_DIR }}/CT222_hadolint_output.txt
          output=$(cat ${{ env.ARTIFACT_DIR }}/CT222_hadolint_output.txt | grep hadolint | awk '{print $2}' | sort -u)

          echo "hadolint_output<<EOF" >> $GITHUB_ENV
          echo "$output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Print Hadolint Results in Job Summary
        shell: bash
        run: |
          set -x
          echo "### Hadolint Returned Rule Codes" > $GITHUB_STEP_SUMMARY
          echo "${{ env.hadolint_output }}" >> $GITHUB_STEP_SUMMARY
      - name: Upload Hadolint Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SDL Evidence
          path: ${{ env.ARTIFACT_DIR }}/CT222_hadolint_output.txt
      - name: Cleanup
        if: always()
        run: |
          rm -rf ${GITHUB_WORKSPACE}/.git* ${GITHUB_ACTION_PATH} || true
          rm -rf /tmp/tmp-* ${GITHUB_WORKSPACE}/*  || true

  Bandit:
    name: Run Bandit
    needs: delete
    runs-on:
      group: intellabs-vdms-runners
      labels: vdms-check-in
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v1
        # with:
        #   ref: ${{ env.CHECKOUT_REF }}
      - name: Run Bandit
        id: bandit
        run: |
          python3 -m pip install --user bandit
          mkdir -p ${{ env.ARTIFACT_DIR }}
          bandit ./ -r -c .github/workflows/ipas_default.config -f csv -o ${{ env.ARTIFACT_DIR }}/bandit_report.csv
      - name: Upload Bandit Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SDL Evidence
          path: ${{ env.ARTIFACT_DIR }}/bandit_report.csv
      - name: Cleanup
        # cf. https://github.com/actions/upload-artifact/issues/256
        if: always()
        run: |
          rm -rf ${GITHUB_WORKSPACE}/.git* ${GITHUB_ACTION_PATH} || true
          rm -rf /tmp/tmp-* ${GITHUB_WORKSPACE}/*  || true

  # BUILD LATEST CODE AS DOCKER IMAGE
  # USED WITH TRIVY, CIS, & BDBA JOBS
  BuildLatest:
    # This job builds docker container for later use
    name: Build Latest Docker
    needs: delete
    runs-on:
      group: intellabs-vdms-runners
      labels: vdms-check-in
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          submodules: true
          # ref: ${{ env.CHECKOUT_REF }}
      - run: mkdir -p ${{ env.DOCKER_ARTIFACT_DIR }}
      - name: Build Docker Container
        run: |
          docker build --rm --build-arg="BUILD_COVERAGE=off" --build-arg="BUILD_COVERITY=off" \
            -f ${{ env.CHECKIN_DOCKERFILE}} -t vdms:latest .
          docker save -o ${{ env.DOCKER_ARTIFACT_DIR }}/vdms_latest.tar vdms:latest
      - name: Upload Docker Image Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: vdms_latest.tar
          path: ${{ env.DOCKER_ARTIFACT_DIR }}/vdms_latest.tar
          retention-days: 1
      - name: Cleanup
        if: always()
        run: |
          rm -rf ${GITHUB_WORKSPACE}/.git* ${GITHUB_ACTION_PATH} || true
          rm -rf /tmp/tmp-* ${{ env.DOCKER_ARTIFACT_DIR }} ${GITHUB_WORKSPACE}/*  || true
          docker rmi $(docker images | grep '<none>' | awk '{print $3}') || true

  BDBA:
    # CT7
    runs-on:
      group: intellabs-vdms-runners
      labels: vdms-check-in
    name: BDBA
    needs: BuildLatest
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v3
        with:
          name: vdms_latest.tar
          path: ${{ env.DOCKER_ARTIFACT_DIR }}
      - name: Run BDBA
        id: bdba
        continue-on-error: true
        env:
          BDBA_TOKEN: "${{ secrets.BDBA_TOKEN }}"
          bdba_group: '90'
          bdba_product_id: ${{ secrets.BDBA_PRODUCT_ID }}
        shell: bash
        run: |
          apt-get update && apt-get install -y curl
          curl -k -H "Authorization: Bearer $BDBA_TOKEN" -H "Group: $bdba_group" -H "Replace: $bdba_product_id" -T ${{ env.DOCKER_ARTIFACT_DIR }}/vdms_latest.tar "https://bdba001.icloud.intel.com/api/upload/"
      - name: BDBA Failure Check
        if: failure()
        run: echo "Check BDBA Server(https://bdba001.icloud.intel.com/) for binary vdms_latest.tar"
      - run: |
          rm -rf ${GITHUB_WORKSPACE}/.git* ${GITHUB_ACTION_PATH} || true
          rm -rf /tmp/tmp-* ${{ env.DOCKER_ARTIFACT_DIR }} ${GITHUB_WORKSPACE}/* || true

  Trivy:
    # This job runs Trivy for Vulnerabilities (Replaces Snyk) for CT247, CT248 and SBOM for CT37
    name: Trivy Scan for Vulnerabilities
    needs: BuildLatest
    runs-on:
      group: intellabs-vdms-runners
      labels: vdms-check-in
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          submodules: true
          # ref: ${{ env.CHECKOUT_REF }}
      - run: mkdir -p ${{ env.DOCKER_ARTIFACT_DIR }} ${{ env.ARTIFACT_DIR }}
      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: vdms_latest.tar
          path: ${{ env.DOCKER_ARTIFACT_DIR }}
      - name: Load Docker Image
        run: docker load -i ${{ env.DOCKER_ARTIFACT_DIR }}/vdms_latest.tar
      - name: Run Trivy vulnerability scanner
        run: |
          # Exporting Fixable Results as CSV (For SDL)
          docker run $DOCKER_PROXY_RUN_ARGS \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.cache:/root/.cache \
            -v $PWD:/local_repo aquasec/trivy:latest image \
            --list-all-pkgs --ignore-unfixed --format template \
            --template @/local_repo/.github/workflows/trivy_csv.tmpl \
            --output /local_repo/trivy-report-imagescan_CT247_CT248.csv vdms:latest

          mv /local_repo/trivy-report-imagescan_CT247_CT248.csv ${{ env.ARTIFACT_DIR }}/trivy-report-imagescan_CT247_CT248.csv

          # Obtain Summary Result
          output_checks=$(docker run $DOCKER_PROXY_RUN_ARGS \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.cache:/root/.cache \
            -v $PWD:/local_repo aquasec/trivy:latest image \
            --ignore-unfixed --scanners vuln vdms:latest | grep "Total:")

          echo "trivy_image_results<<EOF" >> $GITHUB_ENV
          echo "$output_checks" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Upload Trivy Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SDL Evidence
          path: ${{ env.ARTIFACT_DIR }}/trivy-report-imagescan_CT247_CT248.csv
          if-no-files-found: error
      - name: Get Docker Image SBOM
        run: |
          docker sbom --format spdx-tag-value --output ${{ env.ARTIFACT_DIR }}/sbom_docker_CT36.txt vdms:latest

          python3 ${GITHUB_WORKSPACE}/docker/check-in/spdx2csv.py -i ${{ env.ARTIFACT_DIR }}/sbom_docker_CT36.txt \
            -o ${{ env.ARTIFACT_DIR }}/vdms_sbom_docker_CT36.csv

          output_checks=$(echo "SBOM Total packages: $(($(cat ${{ env.ARTIFACT_DIR }}/vdms_sbom_docker_CT36.csv | wc -l)-1))")
          echo "sbom_image_results<<EOF" >> $GITHUB_ENV
          echo "$output_checks" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SDL Evidence
          path: ${{ env.ARTIFACT_DIR }}
          if-no-files-found: error
      - name: Print Results in Job Summary
        run: |
          echo "### Results" > $GITHUB_STEP_SUMMARY
          echo "Vulnerability Scan (fixable) :point_right:${{ env.trivy_image_results }}" >> $GITHUB_STEP_SUMMARY
          echo "SBOM :point_right:${{ env.sbom_image_results }}" >> $GITHUB_STEP_SUMMARY

      - name: Cleanup
        if: always()
        run: |
          rm -rf ${GITHUB_WORKSPACE}/.git* ${GITHUB_ACTION_PATH} || true
          rm -rf /tmp/tmp-* ${{ env.DOCKER_ARTIFACT_DIR }} ${GITHUB_WORKSPACE}/*  || true

  CIS:
    # This job runs CIS Docker Benchmark
    name: CIS Docker Benchmark
    needs: BuildLatest
    runs-on:
      group: intellabs-vdms-runners
      labels: vdms-check-in
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v3
        with:
          name: vdms_latest.tar
          path: ${{ env.DOCKER_ARTIFACT_DIR }}
      - name: Load Docker Image
        run: |
          docker load -i ${{ env.DOCKER_ARTIFACT_DIR }}/vdms_latest.tar
      - name: Run Benchmark
        id: run_CIS
        run: |
          set -x
          mkdir -p ${{ env.ARTIFACT_DIR }}
          git clone https://github.com/docker/docker-bench-security.git
          cd docker-bench-security

          docker container run --net=host -d \
            --security-opt=no-new-privileges \
            --health-cmd='cd /vdms/build && ./vdms || exit 1' \
            --restart on-failure:5 \
            --name vdms_test-CIS vdms:latest

          sh docker-bench-security.sh -c container_runtime -i vdms_test-CIS -l ../${{ env.ARTIFACT_DIR }}/CT249_CIS_report.txt
          cd ..

          output_checks=$(cat ${{ env.ARTIFACT_DIR }}/CT249_CIS_report.txt | grep "Checks:" | sed 's/^.*Checks/Checks/')
          output_score=$(cat ${{ env.ARTIFACT_DIR }}/CT249_CIS_report.txt | grep "Score:" | sed 's/^.*Score/Score/')

          echo "cis_output_checks<<EOF" >> $GITHUB_ENV
          echo "$output_checks" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "cis_output_score<<EOF" >> $GITHUB_ENV
          echo "$output_score" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Upload CIS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SDL Evidence
          path: ${{ env.ARTIFACT_DIR }}/CT249_CIS_report.txt
      - name: Print CIS Results in Job Summary
        shell: bash
        run: |
          echo "### CIS Docker Results" > $GITHUB_STEP_SUMMARY
          echo "${{ env.cis_output_checks }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ env.cis_output_score }}" >> $GITHUB_STEP_SUMMARY
      - name: Cleanup
        # cf. https://github.com/actions/upload-artifact/issues/256
        if: always()
        run: |
          docker stop vdms_test-CIS && docker rm vdms_test-CIS || true
          docker rmi $(docker images | grep '<none>' | awk '{print $3}') || true
          rm -rf ${GITHUB_WORKSPACE}/.git* ${GITHUB_ACTION_PATH} || true
          rm -rf /tmp/tmp-* ${{ env.DOCKER_ARTIFACT_DIR }} ${GITHUB_WORKSPACE}/*  || true

  # BUILD LATEST CODE WITH COVERITY AS DOCKER IMAGE
  Coverity:
    name: Run Coverity
    runs-on:
      group: intellabs-vdms-runners
      labels: vdms-check-in
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          submodules: true
          # ref: ${{ env.CHECKOUT_REF }}
      - name: Build Docker Container with Coverity
        run: |
          docker build --rm --build-arg="BUILD_COVERAGE=off" --build-arg="BUILD_COVERITY=on" \
            -f ${{ env.CHECKIN_DOCKERFILE}} -t vdms:coverity .

      - name: Run Coverity with GCC
        env:
            DOCKER_PROXY_RUN_ARGS: "--env HTTPS_PROXY=$HTTPS_PROXY \
                    --env https_proxy=$https_proxy \
                    --env HTTP_PROXY=$HTTP_PROXY \
                    --env http_proxy=$http_proxy \
                    --env NO_PROXY=${{ secrets.NO_PROXY }} \
                    --env no_proxy=${{ secrets.NO_PROXY }}"
        run: |
          docker run ${{ env.DOCKER_PROXY_RUN_ARGS }} -d --rm --name vdms_test-Coverity \
            --env FACELESS_USERNAME=${{ env.FACELESS_USERNAME}} \
            --env FACELESS_AUTHKEY="${{ env.FACELESS_AUTHKEY}}" \
            --env COVERITYSERVER=${{ env.COVERITYSERVER}} \
            --env COVERITYSTREAM=${{ env.COVERITYSTREAM }} vdms:coverity

          # Configure
          docker exec -w /vdms/build vdms_test-Coverity bash -c "mkdir -p /coverity-results && cov-configure -gcc && cov-configure --compiler c++ --comptype g++ --template"

          # Build
          docker exec -w /vdms/build vdms_test-Coverity bash -c "rm -rf * && cmake .. && cov-build --dir /coverity-results make"

          # Analyze
          docker exec vdms_test-Coverity bash -c "cov-analyze --dir /coverity-results --concurrency --security --rule --enable-constraint-fpp --enable-fnptr --enable-virtual"

          # Commit
          docker exec vdms_test-Coverity bash -c "cov-commit-defects --dir /coverity-results --stream ${COVERITYSTREAM} --url ${COVERITYSERVER} --user ${FACELESS_USERNAME} --password ${FACELESS_AUTHKEY} --debug"

      - name: Cleanup
        # cf. https://github.com/actions/upload-artifact/issues/256
        if: always()
        run: |
          docker stop vdms_test-Coverity && docker rm vdms_test-Coverity || true
          docker rmi $(docker images | grep '<none>' | awk '{print $3}') || true
          rm -rf ${GITHUB_WORKSPACE}/.git* ${GITHUB_ACTION_PATH} || true
          rm -rf /tmp/tmp-* ${{ env.DOCKER_ARTIFACT_DIR }} ${GITHUB_WORKSPACE}/*  || true

